# Generated by Django 3.0.8 on 2020-07-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_playlist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist',
            field=models.CharField(choices=[('5ewPBf43Zo5cOzSM5rx1ED', 'KPOP'), ('4w1j2BzPxQu3Oe9cLhdu92', 'KRnB/Chill/Soft'), ('6XoFinWoj4OSsuldwInjx8', 'TWICE Best Tracks'), ('3NlVy5l5RljnI9eVxD1LeQ', 'Best of IU'), ('1jPeUmbzsHBcLSXuMM3kx4', 'My Shazam Tracks'), ('0uDvOrzlWzI4jlEqLcumUU', 'Dear Remy,')], max_length=30),
        ),
    ]
