# Generated by Django 3.0.8 on 2020-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200723_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
